### PR TITLE
Improve readme fix #36

### LINKED ISSUE #36: Introduce how to work with the solution in the readme

### PR DESCRIPTION
**Pull request by alorma**
https://github.com/gitskarios/quitnow-email-suggester/blob/improve_readme/README.md

### CODE REVIEW

**Comment by rocboronat** [comment]
Thanks for the work @alorma! Btw, the validation secton has one syntax and the suggest one has another one. Can we use only one syntax to describe the result? Btw, i prefer the "result -> value" one.

**Comment by alorma** [comment]
Ok!

**Comment by rocboronat** [comment]
Wep! It's only a personal preference :-) Don't know what are the most common way to explain it. But well, the idea is to only have one way to explain it.

Again, thanks for the work, @alorma !

**Comment by rocboronat** [comment]
Wep! One week without news.

**Comment by alorma** [comment]
Sorry i've been busy :)

I will update this in a few days, i'm in a holidays

**Comment by alorma** [comment]
DOne @rocboronat

**Comment by alorma** [comment]
Any news @rocboronat?

**Comment by rocboronat** [comment]
Wep! The example you written is hard to read. Probably people will try to guess why @bananas.con is not replaced by @bananas.com, with an ending "m" instead of an "n".

Here's a screenshot of the whole thing:

image

Let me get some time to improve it please. BTW, thanks for the PR!

**Comment by rocboronat** [comment]
Wep @alorma ! Just released a new README. I think that it's more self-explainatory than yours. Hope you think the same about it!

Thanks for your interest BTW :·)

**Pull request closed without merging**
